### ISSUE TITLE
teslaarsenal{1.1} crashes dedicated Forge 1.10.2 build 2018 on startup

### ISSUE THREAD

**Issue by kreezxil** [knoxhack/Tesla-Arsenal#2]
I know why this is happening, it's because tesla itself has been updated, so you need to recompile.

crash report:
https://gist.github.com/2c5bc3132c8992dfac747247723e0392

fml server latest:
https://gist.github.com/135edf5b54ba201a83f80414b098dd96

**Comment by knoxhack** [comment]
Fixed: https://github.com/knoxhack/Tesla-Arsenal/commit/28c81d4319c55936544a14476a8c94d134a407c2

**Comment by knoxhack** [comment]
Update to Tesla Arsenal version 1.2
